<a href="https://colab.research.google.com/github/emrecicekyurt/heart-disease-classification/blob/main/heart_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [90]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Reading Dataset


In [91]:
dataset = pd.read_csv('heart_2020_cleaned.csv')
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

print(X)
print(y)

[[16.6 'Yes' 'No' ... 'Yes' 'No' 'Yes']
 [20.34 'No' 'No' ... 'No' 'No' 'No']
 [26.58 'Yes' 'No' ... 'Yes' 'No' 'No']
 ...
 [24.24 'No' 'No' ... 'No' 'No' 'No']
 [32.81 'No' 'No' ... 'No' 'No' 'No']
 [46.56 'No' 'No' ... 'No' 'No' 'No']]
['No' 'No' 'No' ... 'No' 'No' 'No']


Encoding Dependent Variable

In [92]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 ... 0 0 0]


Encoding Dependent Variable

In [93]:
from sklearn.preprocessing import OneHotEncoder
independent_variables_encoding_list = [1, 2, 3, 6, 7, 8, 9, 10, 
                               11, 12,14, 15, 16]

for feature in independent_variables_encoding_list:
    X[:,feature] = le.fit_transform(X[:,feature])

print(X)

[[16.6 1 0 ... 1 0 1]
 [20.34 0 0 ... 0 0 0]
 [26.58 1 0 ... 1 0 0]
 ...
 [24.24 0 0 ... 0 0 0]
 [32.81 0 0 ... 0 0 0]
 [46.56 0 0 ... 0 0 0]]


Splitting data for testing and training

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train[0])

[19.53 1 1 0 0.0 0.0 0 0 9 5 0 1 0 9.0 0 0 1]


Scaling the data

In [95]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)


Training the model

In [96]:
# Logistic Regression beated other models in terms of accuracy like KNN, Naive Bayes, Decision Tree and Random Forest Tree.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

Displaying the predictions

In [97]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


Computing confusion matrix and accuracy score

In [98]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[58041   471]
 [ 4970   477]]


0.9149298769524227

A sample prediction below

In [99]:
print(classifier.predict(sc.transform([[16.6, 1, 0, 0, 3.0, 30.0, 0, 0, 7, 5, 2, 1, 4, 5.0, 1, 0, 1]])))

[0]
